blogify/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts" # namespace

urlpatterns = [
    path('signup/', views.account_signup, name="signup"),
    path('login/', views.account_login, name="login"),
    path('logout/', views.account_logout, name="logout"),
]

blogify/blogify/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from posts import views as post_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # include the accounts urls from the accounts app
    path('posts/', include('posts.urls')), # include the posts.urls from the posts app
    path('about/', views.about),
    path('', post_views.post_list, name="home"), # r'^$'
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogify/posts/urls.py
from django.urls import path
from . import views


app_name = "posts" # namespace

urlpatterns = [
    path('', views.post_list, name="list"),
    path('create/', views.post_create, name="create"), # fires this url first instead of slug
    path('own/', views.post_own, name="own"),
    path('<slug:slug>/', views.post_detail, name="detail"),
]

blogify/accounts/models.py
from django.db import models

# Create your models here.

blogify/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True) # auto set time when post is created
    image = models.ImageField(default="default.jpeg", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.title

    def post_snippet(self):
        return self.body[:100] + "..." # show a snippet of the post

blogify/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'image']

        

blogify/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.



def account_signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid(): #  checks if the form valid or invalid
            user = form.save()
            login(request, user)
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", { 'form' : form })


def account_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST: # redirect to next position
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")

    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {'form' : form})

def account_logout(request):
    if request.method == "POST":
        logout(request) # logout the current user
        return redirect ("posts:list")

blogify/blogify/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")

blogify/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Post
from . import forms

# Create your views here.

def post_list(request):
    posts = Post.objects.all().order_by("-date") # grabs all posts from db ordered by date
    return render(request, "posts/post_list.html", {"posts": posts}) # create dic to send to template with data retrieved from db

def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html', {'post' : post }) # retrieves content for each post

@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == "POST": # when the submit btn is pressed
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user # set the current logged in user as the post writer
            instance.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, "posts/post_create.html", { 'form' : form })

@login_required(login_url="/accounts/login")
def post_own(request):
    posts = Post.objects.filter(author=request.user) # filter posts by current logged in user
    return render(request, "posts/post_own.html", {"posts": posts})

blogify/accounts/templates/accounts/login.html
{% extends 'base.html' %}



{% block content %}

<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
</form>

{% endblock %}

blogify/accounts/templates/accounts/signup.html
{% extends 'base.html' %}



{% block content %}

<h1>Sign up</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
</form>

{% endblock %}

blogify/posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<h2>Create New Post: </h2>
<div class="post-create">
    <form class="site-form" action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

blogify/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="post-detail">
    <div class="post">
        <img src="{{post.image.url }}"/>
        <h2>{{post.title}}</h2>
        <p>{{post.date}}</p>
        <p class="author"><b>By {{post.author.username}}</b></p>
        <p>{{post.body}}</p>
    </div>

</div>

{% endblock %}

blogify/posts/templates/posts/post_list.html
{% extends 'base.html' %}


{% block content %}
<h1>Blogify</h1>
<p>List of posts made by others</p>
<div class"posts">
  {% for post in posts %}

  <div class="post">
    <h2><a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a></h2>
    <p> {{ post.date }} </p>
    <p> {{ post.post_snippet }} </p>
  </div>

  {% endfor  %}
</div>
{% endblock %}

blogify/posts/templates/posts/post_own.html
{% extends 'base.html' %}


{% block content %}
<h2>My Posts: </h2>
 <div class="posts">
  {% for post in posts %}
  <a href="{% url 'posts:detail' slug=post.slug %}">
  <div class="post">
    
    <h2>{{ post.title }}</h2>
    <img src="{{post.image.url }}"/>
    <p class="date"> {{ post.date }} </p>
    <p class="author"><b> By {{ post.author.username }}</b></p>
    <p> {{ post.post_snippet }} </p>
  </div>
  </a>
  {% endfor  %}
 </div>
 {% endblock %}

blogify/templates/about.html
<!doctype html>

<head>
  <meta charset="utf-8">
  <title>Blogify - About</title>

</head>

<body>
<h1>Blogify</h1>
<p>This is the about page</p>
</body>

</html>

blogify/templates/base.html
{% load static from staticfiles %}

<!doctype html>

<head>
  <meta charset="utf-8">
  <title>Blogify - Posts</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <header class="wrapper">
        <a href="{% url 'home' %}"><img src="{% static 'blogify.png' %}" /></a>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'posts:list' %}">Browse</a>
                </li>
                <li>
                    <a href="{% url 'posts:create' %}" class="highlight">Create New Post</a>
                </li>
                <li>
                    <a href="{% url 'posts:own' %}" class="highlight">My Posts</a>
                </li>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                {% else %}
                <li>
                    
                    <a href="{% url 'posts:list' %}">Browse Posts</a>
                    <a href="{% url 'accounts:login' %}">Login</a>
                    <a href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
    </html>

blogify/templates/home.html
<!doctype html>

<head>
  <meta charset="utf-8">
  <title>Blogify - Home</title>

</head>

<body>
<h1>Blogify</h1>
<p>Welcome!</p>
</body>

</html>